---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true
dist: xenial

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint tasks/main.yml

  # Basic role syntax check
  - ansible-playbook -i tests/vagrant/inventory tests/vagrant/test.yml --syntax-check --list-tasks

  # Run the role/playbook with ansible-playbook
  - ansible-playbook -i tests/vagrant/inventory tests/vagrant/test.yml --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent
  - >
    ansible-playbook -i tests/vagrant/inventory tests/vagrant/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Make sure emby is running
  - >
    curl --insecure -s -o /dev/null -w "%{http_code}" https://localhost/users/password/new
    | grep -q '200'
    && (echo 'Status code 200 test: pass' && exit 0)
    || (echo 'Status code 200 test: fail' && exit 1)

  - cat /etc/emby-server.conf

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/