---
# tasks file for emby

# Add the user with a primary group
- group:
    name: "{{ emby_group }}"
    state: present

- user:
    name: "{{ emby_user }}"
    comment: "emby-server user"
    group: "{{ emby_group }}"
    state: present

- name: Install {{ emby_service }}
  include: ubuntu_packages.yml
  when: ansible_distribution == "Ubuntu"

- name: Update {{ emby_service }} configuration file
  become: yes
  blockinfile:
    dest: /etc/{{ emby_service }}.conf
    block: "{{ lookup('template', 'templates/emby_server_conf.j2') }}"
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
  notify: restart emby

